#! /bin/bash

if [ -f $1 ]; then
    echo "exist"
    abspath=$(cd $(dirname $1) && pwd)/$(basename $1)
    echo ${abspath}
    python /opt/sim-plot.py ${abspath}
else
    echo "file does not exist"
fi

