#! /bin/bash

if [ $# -ne 2 ];then
    echo "Usage: optimize <input file> <output file>";
    echo "If there is no output file, create one.\nAn input file is always required.";
    exit 1
fi


if [ -f $1 ]; then
    echo "exist"
    abspath=$(cd $(dirname $1) && pwd)/$(basename $1)
    echo ${abspath}
    python /opt/optimizer.py ${abspath}
else
    echo "file does not exist"
fi

